<?php

namespace OC\PlatformBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAdverts($page, $nbPerPage)
    {
        $query = $this->createQueryBuilder('a')
            ->leftJoin('a.image', 'i')
            ->addSelect('i')
            ->leftJoin('a.categories', 'c')
            ->addSelect('c')
            ->orderBy('a.date', 'DESC')
            ->getQuery();

        $query
            ->setFirstResult(($page-1) * $nbPerPage)
            ->setMaxResults($nbPerPage);

        return new Paginator($query, true);

    }

    public function getAdvertWithCategories($categoryId)
    {

        $qb = $this->createQueryBuilder('a');

        $qb
            ->addSelect('c')
            ->innerJoin('a.categories', 'c')
            ->where('c.id = :categoryId')
            ->setParameter(':categoryId', $categoryId);

        return $qb->getQuery()->getResult();
    }
}
