<?php

namespace OC\PlatformBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAdvertWithCategories($categoryNames)
    {

        $qb = $this->createQueryBuilder('a');

        echo 'aaaa';
        echo (var_dump($qb->getQuery()->getSQL(), true));
        die();

        $qb->innerJoin('a.categories', 'c')->addSelect('c');

        $qb->where('c.name = :categoryNames')->setParameter(':categoryNames', $categoryNames);

        return $qb->getQuery()->getResult();
    }
}
