<?php

namespace OC\PlatformBundle\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAcpplicationsWithAdvert($limit)
    {
        return $this->createQueryBuilder('a')
                ->innerJoin('a.advert', 'adv')
                ->addSelect('adv')
                ->getQuery()
                ->getResult();

    }
}
